title: Yukinyaa # Site title
description: yukinyaa's personal page
baseurl: "" # If your blog is built under a specific directory, add that directory name here, and also add it to all links below that start with `/assets`, e.g., `/your_baseurl/assets`. Don't add a trailing '/'.

defaults: # Configure all settings using <https://jekyllrb.com/docs/configuration/front-matter-defaults/>
  - scope:
      path: "" # An empty string here means all files in the project
    values: # The following options can also be customized per page
      jekyll-theme-WuK: # Custom styles for this theme are under this namespace
        comments: # Comment section — change this to your own repo! See <https://giscus.app/>
          append: |
            <div class="giscus">
              Loading comments...
            </div>
            <script src="https://giscus.app/client.js"
                    data-repo="yukinyaa/yukinyaa.github.io"
                    data-repo-id="R_kgDOPGkChQ"
                    data-category="General"
                    data-category-id="DIC_kwDOPGkChc4Cscqg"
                    data-mapping="pathname"
                    data-strict="0"
                    data-reactions-enabled="1"
                    data-emit-metadata="0"
                    data-input-position="bottom"
                    data-theme="preferred_color_scheme"
                    data-lang="ko"
                    crossorigin="anonymous"
                    async>
            </script>
        default:
          html_lang: zh # Language code: <https://www.w3school.com.cn/tags/html_ref_language_codes.asp>
          color-mode: auto # <https://primer.style/css/storybook/?path=/docs/support-theming--docs>
          light-theme: light
          dark-theme: dark
          menu:
            nav: # Navigation content — you can add your own links
              - title: 'Index'
                href: /
              - title: 'Comments'
                href: /comments/
              - title: 'Archive'
                href: /archive/
              - title: 'Tags'
                href: /tags/
              - title: 'GitHub'
                href: https://github.com/Yukinyaa
              - title: 'X(twitter)'
                href: https://x.com/_Yukinyaa
            footer: | # Site visit statistics
              <div>
                <span id="busuanzi_container_site_pv">
                  <span id="busuanzi_value_site_pv"></span>
                  visits
                </span>
                <span id="busuanzi_container_site_uv">
                  <span id="busuanzi_value_site_uv"></span>
                  vistors
                </span>
                <script
                  src="https://cdn.jsdelivr.net/npm/busuanzi@2.3/bsz.pure.mini.js"
                  async="async"
                ></script>
              </div>
              <div>
                (C) 2017-2025 wu-kan
              </div>
            jekyll-toc: # <https://github.com/allejo/jekyll-toc>
              enable: true
              prepend: |
                <style>
                  #wrap-toc {
                    padding-left: 3em;
                  }
                </style>
            prepend:
              - | # Search box
                <form class="SelectMenu-filter">
                  <input
                    class="SelectMenu-input form-control"
                    type="text"
                    placeholder="Search"
                    aria-label="Filter"
                    id="wrap-search-input"
                  />
                  <ol class="px-5" id="wrap-search-result"></ol>
                  <script
                    src="https://cdn.jsdelivr.net/npm/simple-jekyll-search@1.10.0/dest/simple-jekyll-search.min.js"
                    async="async"
                    onload='
                  SimpleJekyllSearch({
                    json: "/assets/simple-jekyll-search/search.json",
                    searchInput: document.getElementById("wrap-search-input"),
                    resultsContainer: document.getElementById("wrap-search-result"),
                    searchResultTemplate: `<li><a href="{url}">{title}</a></li>`,
                    limit: 9
                  })'
                  ></script>
                </form>
          append_to_head: # Embed plugins with inline HTML — be sure you know what you're doing. See <https://wu-kan.cn/2019/01/18/基于Jekyll搭建个人博客/>
            - | # Page loading animation — you can find one at <https://css-loaders.com/>
              ...
            - | # Some meta tags for page optimization — you can skip if unsure
              ...
            - | # Styles from primer/css — do not modify
              ...
            - | # Syntax highlighting — choose a theme from <https://www.npmjs.com/package/pygments-rouge-css>
              ...
            - | # Fonts
              ...
            - | # Fill page height
              ...
        page:
          title: # Automatically generate H1 title for each page
            enable: true
          prepend:
            - | # First line indentation, adjust image size
              ...
            - |
              ...
          plugin:
            - smart_include:
                enable: true
                key: $
              append: | # Fix for KaTeX long formulas overflowing page. Thanks to [@AmachiInori](https://github.com/wu-kan/wu-kan.github.io/issues/13)
                ...
            - smart_include:
                enable: true
                key: language-vega-lite
              append: |
                ...
            - smart_include:
                enable: true
                key: language-mermaid
              append: |
                ...
            - smart_include:
                enable: false
              append: |
                ...
        post:
          date: # Show post date
            enable: true
            prepend: post on
          wordcount: # Count total word count
            enable: true
            prepend: about
            unit: words
          readtime: # Estimate reading time
            enable: true
            prepend: require
            unit: min
            divided_by: 300 # Normal reading speed: ~300 words per minute
          copyright: |
            My posts are under the most permissive Creative Commons license: Attribution 4.0 International (CC BY 4.0)
          related_posts:
            enable: true
        home: # Settings for slide-based homepage — optional, see <https://revealjs.com/>
          ...
#compress_html: # <https://github.com/penibelst/jekyll-compress-html>
#    comments: [] # Comments can't be compressed or reveal.js slide transitions may break

# Plugins supported by GitHub Pages: <https://pages.github.com/versions/>
#plugins:
#  ...

remote_theme: https://github.com/wu-kan/jekyll-theme-WuK@5.4.0 # Use a fixed theme version to prevent layout issues due to updates

paginate: 10
paginate_path: "/assets/history/:num/"

readme_index: # Use README.md as index when index.md/index.html is missing
  with_frontmatter: true # Support YAML frontmatter in README

webmaster_verifications: # <https://jekyll.github.io/jekyll-seo-tag/usage/>
  google: YIKi1rBnyUaS-DMYiluseI5kZzTwjCkTFmKkSkMZDJk
  baidu: szbTSfUGAB

permalink: pretty
timezone: Asia/Shanghai # Fix incorrect time on GitHub Pages — see <https://www.iana.org/time-zones>
future: true # Allow scheduling future-dated posts

# limit_posts: 999 # Limit the number of posts shown
# encoding: utf-8

markdown: kramdown
kramdown: # See <https://kramdown.gettalong.org/options.html>
  input: GFM # See <http://jekyllcn.com/docs/configuration/#kramdown>
  syntax_highlighter_opts: # See <https://kramdown.gettalong.org/syntax_highlighter/rouge.html>
    block:
      disable: false
      line_numbers: true
    span:
      disable: false

# The following are unchangeable parameters on GitHub Pages: <https://help.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll>
#lsi: false
#safe: true
#source: [your repo's top level directory]
#incremental: false
#highlighter: rouge
#gist:
#  noscript: false
#kramdown:
#  math_engine: mathjax
#  syntax_highlighter: rouge